name: 🐛 Bug report
description: Report a bug or regression
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
      description: What happened?
      placeholder: Explain the bug clearly...
  - type: input
    attributes:
      label: Version
      placeholder: e.g., 0.2.0
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: Step-by-step reproduction
  - type: textarea
    attributes:
      label: Expected behavior
  - type: textarea
    attributes:
      label: System details
      placeholder: OS, Cargo version, Rust version
